#include "__cf_normal_operation_no_faults.h"
#ifndef RTW_HEADER_normal_operation_no_faults_acc_types_h_
#define RTW_HEADER_normal_operation_no_faults_acc_types_h_
#include "rtwtypes.h"
#include "multiword_types.h"
typedef struct P_Subsystempi2delay_normal_operation_no_faults_T_
P_Subsystempi2delay_normal_operation_no_faults_T ; typedef struct
P_Subsystem1_normal_operation_no_faults_T_
P_Subsystem1_normal_operation_no_faults_T ; typedef struct
P_Subsystempi2delay_normal_operation_no_faults_h_T_
P_Subsystempi2delay_normal_operation_no_faults_h_T ; typedef struct
P_Subsystem1_normal_operation_no_faults_g_T_
P_Subsystem1_normal_operation_no_faults_g_T ; typedef struct
P_Subsystempi2delay_normal_operation_no_faults_l_T_
P_Subsystempi2delay_normal_operation_no_faults_l_T ; typedef struct
P_Subsystem1_normal_operation_no_faults_h_T_
P_Subsystem1_normal_operation_no_faults_h_T ; typedef struct
P_ZeroSequenceController_normal_operation_no_faults_T_
P_ZeroSequenceController_normal_operation_no_faults_T ; typedef struct
P_RMS_normal_operation_no_faults_T_ P_RMS_normal_operation_no_faults_T ;
typedef struct P_TrueRMS_normal_operation_no_faults_T_
P_TrueRMS_normal_operation_no_faults_T ; typedef struct
P_ACVoltageController_normal_operation_no_faults_T_
P_ACVoltageController_normal_operation_no_faults_T ; typedef struct
P_Circulatingcurrentsuppression_normal_operation_no_faults_T_
P_Circulatingcurrentsuppression_normal_operation_no_faults_T ; typedef struct
P_Subsystempi2delay_normal_operation_no_faults_g_T_
P_Subsystempi2delay_normal_operation_no_faults_g_T ; typedef struct
P_Subsystem1_normal_operation_no_faults_j_T_
P_Subsystem1_normal_operation_no_faults_j_T ; typedef struct
P_AutomaticGainControl_normal_operation_no_faults_T_
P_AutomaticGainControl_normal_operation_no_faults_T ; typedef struct
P_HarmonicGenerator_normal_operation_no_faults_T_
P_HarmonicGenerator_normal_operation_no_faults_T ; typedef struct
P_Signalgenerator_normal_operation_no_faults_T_
P_Signalgenerator_normal_operation_no_faults_T ; typedef struct
P_normal_operation_no_faults_T_ P_normal_operation_no_faults_T ;
#endif
